### PR TITLE
Fix whitespace parsing, with enhanced parser debugging

### LINKED ISSUE #36: Can not add css comments at the end
This compiles:
```rust
    let backdrop = css!(
        r#"
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  width: 100%; /* Full width */
  height: 100%;
        "#);
```

This doesn't:

```rust
    let backdrop = css!(
        r#"
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  width: 100%; /* Full width */
  height: 100%; /* Full height */
        "#);
```

compiler output:
```
error: Failed to Parse CSS, due to:
0: at line 5, in Many0:
  height: 100%; /* Full height */
                ^

1: at line 1, in Trimmed:

^

2: at line 1, in StyleSheet:

^


  --> src\main.rs:12:9
   |
12 | /         r#"
13 | |   position: fixed; /* Stay in place */
14 | |   z-index: 1; /* Sit on top */
15 | |   width: 100%; /* Full width */
16 | |   height: 100%; /* Full height */
17 | |         "#);
   | |__________^
```

### PR DESCRIPTION
**Pull request by WorldSEnder**
While working on #36  I noticed a few things about the parser, that are part of this pr, since addressing them helped me understand the issue.

- The helper parser combinators `expect_non_empty`, preferred over the `|i| { Parser::expect_non_empty(i)?` style, and `traced_context`, unifying `#[test] debug!(...)` have been added.
- `Parser::sp` was always used as `opt(Self::sp)` and has been rewritten to reflect that.
- `Parser::sp` now includes comments, which are hence parsed as if they were whitespace. This was the conclusion of asking on the nom gitter how to best ignore comments in arbitrary positions.
- closes #36 

There is potential for a follow up that looks over all the parsers and tries to rewrite things so that `Self::sp` is not called twice at the same input position, but that is not necessarily a part of this, but let me know if I should do that @futursolo.

### CODE REVIEW

File: packages/stylist-core/src/parser.rs [hunk 1]
```diff
@@ -20,46 +20,80 @@ use nom::{
...
         }
     }
+}
+
+/// A lightweight CSS Parser.
+#[derive(Debug)]
+pub(crate) struct Parser {}
 
+// Naming convention:
+// - parsers ending with _ns assume the input has *no space* (superfluous whitespace) at the start
```
Comment (futursolo) [inline packages/stylist-core/src/parser.rs:72]: I am about to add rules in rules and rules in blocks and this behaviour is not desirable when a parser function is used in multiple places.

IMO, The parser function should always try to strip spaces.

So developers do not have to follow naming convention to make sure that the parser is functional.

File: packages/stylist-core/src/parser.rs [hunk 2]
```diff
@@ -20,46 +20,80 @@ use nom::{
...
-#[derive(Debug)]
-pub(crate) struct Parser {}
-
+/// Wrap a parser, tracing input and output.
+// if not cfg(test), this would trip up clippy.
 #[allow(clippy::let_and_return)]
-impl Parser {
-    /// Returns Error when string is Empty
-    fn expect_non_empty(i: &str) -> std::result::Result<(), nom::Err<VerboseError<&str>>> {
+fn traced_context<I, O, F>(
```
Comment (futursolo) [inline packages/stylist-core/src/parser.rs:26]: These two functions (`traced_context` and `expect_non_empty`) should be within the impl block of `Parser`?

File: packages/stylist-core/src/parser.rs [hunk 3]
```diff
@@ -20,46 +20,80 @@ use nom::{
...
+    mut p: impl nom::Parser<I, O, F>,
+) -> impl FnMut(I) -> IResult<I, O, F>
+where
+    I: fmt::Display + fmt::Debug + Clone,
+    O: fmt::Debug,
+    F: fmt::Debug + nom::error::ContextError<I>,
+{
+    move |i| {
+        #[cfg(test)]
+        trace!("> {}: {}", ctx, i);
```
Comment (futursolo) [inline packages/stylist-core/src/parser.rs:37]: Better to give the tracing context a number?

File: packages/stylist-core/src/parser.rs (hunk 1 above)
Comment (futursolo) [reply packages/stylist-core/src/parser.rs:72]: In addition, this convention is not consistent. For example: `ident` parser does not accept any spaces, but does not have `_ns` affix.

**Review by futursolo — CHANGES_REQUESTED** [review]

File: packages/stylist-core/src/parser.rs (hunk 2 above)
Comment (WorldSEnder) [reply packages/stylist-core/src/parser.rs:26]: I moved them outside, cause unlike `Parser::trimmed`, they are general combinators and don't depend on any css parser specifics. Thought that gave a better impression of that fact, nothing wrong with freestanding methods, or am I wrong?

File: packages/stylist-core/src/parser.rs (hunk 1 above)
Comment (WorldSEnder) [reply packages/stylist-core/src/parser.rs:72]: It's trying to avoid trimming multiple times already knowing the input can't be trimmed. I'm wondering, maybe it's better to put that part in a separate PR.

Comment (futursolo) [reply packages/stylist-core/src/parser.rs:72]: The current parser performance is OK to me?

If parser is used at compile time, performance does not matter that much as long as the performance is not horrible.
If parser is used at runtime, IMO, file size is more important than performance as long as the performance is not horrible.

I was actually wondering if we should continue using nom after inspecting the parser used by `emotion` and its code size.

https://github.com/thysultan/stylis.js/blob/master/src/Parser.js

Comment (WorldSEnder) [reply packages/stylist-core/src/parser.rs:72]: Okay, let me convert this PR back into draft and shrink the changes down even more to address specfically the linked bug and improved debugging with `traced_context` only, the rest in another issue, sounds good?

File: packages/stylist-core/src/parser.rs (hunk 2 above)
Comment (futursolo) [reply packages/stylist-core/src/parser.rs:26]: Well, I guess it's OK to have it outside of the `Parser`? Especially given that we may create different parsers for different purposes (e.g.:`keyframes`)

File: packages/stylist-core/src/parser.rs (hunk 1 above)
Comment (futursolo) [reply packages/stylist-core/src/parser.rs:72]: Sounds good to me.

File: packages/stylist-core/src/parser.rs (hunk 3 above)
Comment (WorldSEnder) [reply packages/stylist-core/src/parser.rs:37]: Meaning an indentation level, or number instead of `ctx: &str`, not sure I understand :)

File: packages/stylist-core/src/parser.rs [hunk 4]
```diff
@@ -1200,7 +1059,7 @@ mod tests {
     fn test_comment() {
         init();
         let test_str = r#"
-                /* some comment */
+                /* some comment */ /* another comment */
```
Comment (WorldSEnder) [inline packages/stylist-core/src/parser.rs:1062]: Tests recognizing multiple comments in a row, possibly spaced by whitespace

File: packages/stylist-core/src/parser.rs (hunk 3 above)
Comment (futursolo) [reply packages/stylist-core/src/parser.rs:37]: Sorry that I didn't explain this properly.

Sometimes it's possible to have the following situation:

```
> Rule:
... 
> Rule: 
...
> Rule:
...
> Rule:
...
> Rule:

...

< Rule:
... 
< Rule: 
...
< Rule:
...
< Rule:
...
< Rule:
```

So it might be handy to have a number to keep track of it:

```
> Rule 1:
... 
> Rule 2: 
...
> Rule 3:
...
> Rule 4:
...
> Rule 5:

...

< Rule 5:
... 
< Rule 4: 
...
< Rule 3:
...
< Rule 2:
...
< Rule 1:
```

I think indentation should work as well.
